<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="./img-LOGO.jpg" type="image/x-icon">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="./INICIO.css">
    <title>Inicio/Life S.D.B</title>
</head>
<header>
  <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <a class="navbar-brand" href="INICIO.PHP" style="color: white;">INICIO</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="US.php" style="color: white;">NOSOTROS</a>
            </li>
            <li class="nav-item">
              <a href="LOGIN.php" class="nav-link" style="color: white;">INICIAR SESIÓN</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="SING-UP.php" style="color: white;">REGISTRARSE</a>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled" style="color: yellow;">LIFE S.D.B</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
</header>
<body>
<img src="img-INICIO.png" alt="" width="900px" height="100px" class="img-products" style="margin-left: 250px;  margin-top: 100px" >
<hr>
  <div class="container">
      <div class="Item" id="Item1">
        <img src="img-local.png" alt="" width="350px" height="600px" style="border-radius: 40px;">
      </div>
      <div class="Item" id="Item2">
      <h1 style="color: brown; font-size: 50px; margin-left: 150px;">HORARIOS DE APERTURA</h1>
        <ul  style="font-size: 30px; margin-left: 300px;  margin-top: 50px">
          <li>Lun:	11:00–20:00</li>
          <li>Mar:	11:00–20:00</li>
          <li>Mié:	11:00–20:00</li>
          <li>Jue:	11:00–20:00</li>
          <li>Vie:	11:00–20:00</li>
          <li>Sáb:	10:00–20:00</li>
          <li>Dom:	11:00–20:00</li>
</ul>
      </div>
      <br>
      <br>
      <br>
  </div>
  <div class="container">
      <div class="Item" id="Item1">
      <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3976.
    8962222231735!2d-74.1745243!3d4.612590199999999!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.
    1!3m3!1m2!1s0x8e3f9fadd638b323%3A0x2a9c59fa508893f!2sLife%20S.D.B!5e0!3m2!1ses-
    419!2sco!4v1679851308920!5m2!1ses-419!2sco" width="800" height="600" style="border:0;" 
    allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
      </div>
      <div class="Item" id="Item2">
      <ul>
          <li><a class="btn btn-success" href="https://api.whatsapp.com/send?phone=573138016859" role="button">WHATSAPP</a></li>
          <li></li>
          <li><a class="btn btn-danger" href="#" role="button">INSTAGRAM</a></li>
          <li></li>
          <li><a class="btn btn-info" href="#" role="button">+57 313 8016859</a></li>
      </ul>
      </div>
      </div>
</body>
<footer style="background-color:black">
  <center>
    <p class="derechos text-white">Todos los derechos reservados © 2023 <img
            src="img-LOGO.jpg"
            width="40px" alt=""></p>
    <br>
    <p class="documento text-white" style="font-family: Arial, Helvetica, sans-serif;">Prohibida la reproducción de este documento sin la 
    debida autorización y revisión de LIFE S.D.B y ROBOT LIFE.</p>
    <br>
    <br>

    </center>
    </footer>
</html>